name: ci
on: pull_request

# Secrets:
#   DOCKERHUB_USERNAME - also used as the dockerhub repository url
#   DOCKERHUB_PASSWORD

env:
  HYDRO_SERVING_REPO: Hydrospheredata/hydro-serving-ui
  IMAGE: hydro-serving-ui # name of the built image

jobs:
        
  Setup:
  # Try to load dependecies from cache, install dependecies on cache miss
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
              
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
             
  Test:
    runs-on: ubuntu-latest
    needs: [Setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install npm dependency
        run: npm install 

      - name: Run Jasmine tests
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Comment Test Coverage
        uses: AthleticNet/comment-test-coverage@1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: coverage/coverage-summary.json
          title: Karma Test Coverage
        
  Build_image:
    runs-on: ubuntu-latest
    needs: [Setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: hydrosphere/${{ env.IMAGE }}:${{ github.sha }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}  

      - uses: azure/container-scan@v0
        with:
          image-name: hydrosphere/${{ env.IMAGE }}:${{ github.sha }}
